spring:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: Authorization, Content-Type, X-Total-Count, Content-Disposition
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: 8088

eureka:
  client:
    serviceUrl:
      registerWithEureka: false
      fetchRegistry: true
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true