spring:
  name: eureka

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    instance-info-replication-interval-seconds: 10
  server:
    eviction-interval-timer-in-ms: 50000
    wait-time-in-ms-when-sync-empty: 5