spring:
  application:
    name: auth
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=true:
    hibernate:
      ddl-auto: update

  datasource:
    username: ${DB_USER:rootroot}
    password: ${DB_PASS:rootroot}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    driver-class-name: org.postgresql.Driver

jwt:
  secret: petrenkodima

server:
  port: ${PORT:8089}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    preferIpAddress: true